### ISSUE TITLE
README.md refers to old versions

### ISSUE THREAD

**Issue by jalkanen** [paradoxical-io/cassandra-loader#6]
README.md refers to version 1.1 even when 1.3 is released. Both pom snippet and "get it directly from maven" should probably be updated.

**Comment by jakeswenson** [comment]
fixed in commits: b8c8f1d5b56698e772d28e87d5f75442c13b735f, d6b8053b2cde09baae612385cc0705fdff921a54, 11e4c51e0c6258d12c9f39489e3d5f9fcecd1979

**Comment by jakeswenson** [comment]
Thanks for the report! i think i've caught all the random versions through out!
